apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>K3s Demo - GitOps with ArgoCD</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                margin: 50px; 
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
            }
            .container { 
                max-width: 800px; 
                margin: 0 auto; 
                background: rgba(255,255,255,0.1);
                padding: 30px;
                border-radius: 10px;
                backdrop-filter: blur(10px);
            }
            h1 { color: #fff; text-align: center; }
            .info { background: rgba(255,255,255,0.2); padding: 15px; border-radius: 5px; margin: 10px 0; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 K3s Cluster Demo</h1>
            <div class="info">
                <h3>Deployed via GitOps with ArgoCD!</h3>
                <p><strong>Cluster:</strong> 6-node K3s on Oxide Cloud</p>
                <p><strong>Load Balancer:</strong> NGINX → Traefik</p>
                <p><strong>DNS:</strong> external-dns + cert-manager</p>
                <p><strong>TLS:</strong> Let's Encrypt certificates</p>
            </div>
            <div class="info">
                <h3>Available Demo Services:</h3>
                <ul>
                    <li><a href="https://argocd.virington.com" style="color: #fff;">ArgoCD Dashboard</a></li>
                    <li><a href="https://jupyter.virington.com" style="color: #fff;">Jupyter Notebook</a></li>
                    <li><a href="https://whoami.virington.com" style="color: #fff;">WhoAmI Service</a></li>
                </ul>
            </div>
        </div>
    </body>
    </html>