apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-demo-data-pvc
  namespace: nginx-demo
  labels:
    app: nginx-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-static