---
- name: Add Longhorn Helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Create Longhorn namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: longhorn-system
    state: present

- name: Install Longhorn from Helm repository
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: false
    values: "{{ longhorn_helm_values }}"
