---
- name: Install required dependencies for HTTPS transport and keyring
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - ubuntu-keyring
    state: present
    update_cache: true

- name: Add official NGINX signing key
  shell: curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/nginx-archive-keyring.gpg

- name: Add official NGINX repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu {{ ansible_distribution_release | lower }} nginx"
    state: present
    filename: nginx

- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Ensure modules-enabled directory exists
  ansible.builtin.file:
    path: /etc/nginx/modules-enabled
    state: directory
    mode: "0755"

- name: Ensure NGINX stream module is loaded from correct path
  copy:
    dest: /etc/nginx/modules-enabled/50-stream.conf
    content: |
      load_module /etc/nginx/modules/ngx_stream_module.so;

- name: Ensure NGINX is enabled and running
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: Get list of all node internal IPs
  set_fact:
    traefik_backend_hosts: >-
      {{ groups['k3s_cluster']
         | map('extract', hostvars, ['ansible_default_ipv4', 'address'])
         | list }}

- name: Get Traefik NodePort info
  kubernetes.core.k8s_info:
    kind: Service
    namespace: kube-system
    name: traefik
    kubeconfig: "{{ kubeconfig | default(lookup('env', 'HOME') ~ '/.kube/config') }}"
  register: traefik_info
  delegate_to: localhost
  run_once: true
  become: false

- name: Set Traefik NodePort values
  set_fact:
    traefik_http_nodeport: "{{ traefik_info.resources[0].spec.ports | selectattr('port', 'equalto', 80) | map(attribute='nodePort') | list | first }}"
    traefik_https_nodeport: "{{ traefik_info.resources[0].spec.ports | selectattr('port', 'equalto', 443) | map(attribute='nodePort') | list | first }}"

- name: Fail if traefik_backend_hosts is not defined
  ansible.builtin.fail:
    msg: "traefik_backend_hosts must be defined"
  when: traefik_backend_hosts is not defined

- name: Deploy NGINX HTTP proxy configuration
  ansible.builtin.template:
    src: nginx_k3s_proxy.conf.j2
    dest: /etc/nginx/conf.d/k3s.conf
    mode: "0644"

- name: Remove default NGINX landing page config
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Deploy NGINX stream passthrough config for HTTPS
  ansible.builtin.template:
    src: nginx_k3s_stream.conf.j2
    dest: /etc/nginx/stream.conf
    mode: "0644"

- name: Ensure NGINX includes stream configs
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: 'http {'
    line: '    include /etc/nginx/streams-enabled/*.conf;'
    state: present
    regexp: 'streams-enabled/\\*\\.conf'

- name: Ensure NGINX includes top-level stream config
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: '^worker_processes'
    line: 'include /etc/nginx/stream.conf;'
    state: present
    regexp: 'stream\.conf'

- name: Reload NGINX
  ansible.builtin.service:
    name: nginx
    state: reloaded
