apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whoami-data-pvc
  namespace: whoami
  labels:
    app: whoami
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static