apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-db-pvc
  namespace: jupyterhub
  labels:
    app: jupyterhub
    component: hub-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-static