---
- name: Fix kubeconfig to use external IP for cluster access
  hosts: "{{ groups['server'][0] }}"
  gather_facts: true
  tasks:
    - name: Set first server IP facts on the remote host
      ansible.builtin.set_fact:
        first_internal_ip: "{{ ansible_default_ipv4.address }}"
        first_external_ip: "{{ ansible_host | default(inventory_hostname) }}"
      run_once: true

    - name: Ensure .kube directory exists on control node
      delegate_to: localhost
      run_once: true
      ansible.builtin.file:
        path: "~/.kube"
        state: directory
        mode: "0755"

    - name: Check if kubeconfig exists on control node
      delegate_to: localhost
      run_once: true
      ansible.builtin.stat:
        path: "~/.kube/config"
      register: kubeconfig_exists

    - name: Check if k3s kubeconfig exists on server
      when: not kubeconfig_exists.stat.exists
      run_once: true
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: server_kubeconfig_exists

    - name: Wait for k3s kubeconfig to be created
      when: not kubeconfig_exists.stat.exists and not server_kubeconfig_exists.stat.exists
      run_once: true
      ansible.builtin.wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        timeout: 60

    - name: Ensure k3s kubeconfig is readable for fetch
      when: not kubeconfig_exists.stat.exists
      run_once: true
      become: true
      ansible.builtin.file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: "0644"

    - name: Fetch kubeconfig from server if it doesn't exist on control node
      when: not kubeconfig_exists.stat.exists
      run_once: true
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "~/.kube/config"
        flat: true

    - name: Replace internal IP with external IP in kubeconfig on control node
      delegate_to: localhost
      run_once: true
      ansible.builtin.replace:
        path: "~/.kube/config"
        regexp: "https://{{ hostvars[groups['server'][0]].first_internal_ip }}:6443"
        replace: "https://{{ hostvars[groups['server'][0]].first_external_ip }}:6443"

    - name: Replace localhost with external IP in kubeconfig on control node
      delegate_to: localhost
      run_once: true
      ansible.builtin.replace:
        path: "~/.kube/config"
        regexp: "https://127\\.0\\.0\\.1:6443"
        replace: "https://{{ hostvars[groups['server'][0]].first_external_ip }}:6443"
