---
- name: Fix kubeconfig to use external IP for cluster access
  hosts: "{{ groups['server'][0] }}"
  gather_facts: true
  tasks:
    - name: Set first server IP facts on the remote host
      ansible.builtin.set_fact:
        first_internal_ip: "{{ ansible_default_ipv4.address }}"
        first_external_ip: "{{ ansible_host | default(inventory_hostname) }}"
      run_once: true

    - name: Replace internal IP with external IP in kubeconfig on control node
      delegate_to: localhost
      run_once: true
      ansible.builtin.replace:
        path: "~/.kube/config"
        regexp: "https://{{ hostvars[groups['server'][0]].first_internal_ip }}:6443"
        replace: "https://{{ hostvars[groups['server'][0]].first_external_ip }}:6443"
