---
# cert-manager configuration
cert_manager_challenge_type: "selfsigned"
dns_provider_name: "none"
cert_manager_helm_repo: "https://charts.jetstack.io"
cert_manager_helm_version: "v1.14.5"

# Self-signed certificate configuration
# No additional configuration needed for self-signed certificates
